name: micu
description: "Mic U: Traductor speech-to-speech"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_video_progress_bar: ^0.4.0
  bubble: ^1.2.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_sound: ^8.1.4
  flutter_markdown: ^0.6.2
  get: ^4.1.4
  http: ^0.13.3
  just_audio: ^0.8.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  flutter_svg: ^0.22.0
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/micu_isologo.png